### PR TITLE
Circle CI for deployment

### PR DESCRIPTION
**Pull request by gschorkopf**
Closes https://github.com/atlanta-ember-org/atlanta-ember-backend/issues/17

Some thoughts:
- We'll need further configuration / heroku access on Circle if we want to deploy
- Which begs the question: do we want to use Circle for deployment? Or just running our tests?
- Speaking of tests... they're failing for me locally and on Circle. Something about VCR. That's not really this branch's concern, but...

Also:
- I asked in Slack, but guess I don't quite understand the difference between develop and master branches. Are we pushing to a staging-esque environment first? If that's the case, do we want to be careful with how we continuously deploy?
- Do we wanna turn off email notifications? Are they annoying?

### CODE REVIEW

**Comment by gschorkopf** [comment]
@pdougall1 @camthompson @ultimatemonty :eyes:

**Comment by camthompson** [comment]
I think deploying from Circle makes sense here. Automating deployment makes it clear what is currently deployed and makes sharing/protecting production config easier. It does mean we have to be disciplined about merging API changes that would break the frontend, but I digress.

I don't understand the difference between master/develop without staging either. But it does leave the option of a staging/pre-production environment open.

+100 for turning off email notifications

**Comment by pdougall1** [comment]
staging/pre-production environment == develop

**Comment by gschorkopf** [comment]
Just waiting on the "whether or not to commit the deploy part".

**Comment by pdougall1** [comment]
@gschorkopf I believe we're all happy with continuous deployment :+1:

**Comment by gschorkopf** [comment]
Let's give it a go.

**Pull request merged**
